src/Makefile.am: fix ascii-xfr link with lintl
ascii-xfr needs to link with lintl if needed:

/home/dawncrow/buildroot-test/scripts/instance-0/output/host/bin/m68k-linux-gcc  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2   -W -Wall -Wextra -std=gnu99 -Wno-format-truncation   -o ascii-xfr ascii-xfr.o ../lib/libport.a -lncurses
ascii-xfr.o: In function `stats':
ascii-xfr.c:(.text+0x4c): undefined reference to `libintl_gettext'
ascii-xfr.c:(.text+0xb2): undefined reference to `libintl_gettext'
ascii-xfr.o: In function `usage':
ascii-xfr.c:(.text+0x10e): undefined reference to `libintl_gettext'
ascii-xfr.o: In function `asend':
ascii-xfr.c:(.text+0x534): undefined reference to `libintl_gettext'
ascii-xfr.o: In function `main':
ascii-xfr.c:(.text.startup+0xc8): undefined reference to `libintl_gettext'
ascii-xfr.o:ascii-xfr.c:(.text.startup+0x1a8): more undefined references to `libintl_gettext' follow

Fixes:
 - http://autobuild.buildroot.org/results/e64cdcf648764be53a3e951304bb89dc9410db23

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>